sudo: required

services:
  - docker

before_install:
  - docker pull asciidoctor/docker-asciidoctor

script:
  # compile the headers
  - gcc headers/fmi2Functions.h
  # generate the HTML documentation
  - docker run -v $TRAVIS_BUILD_DIR/docs:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -b html5 fmi_specification.adoc

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html
